#!/usr/bin/env bash
# Kiro CLI adapter. Contract: <role> <task_dir> <workdir> → artifacts + report.
# Roles become generated Kiro custom agents (~/.kiro/agents/harness-<role>.json):
# prompt = the role file, permissions = Kiro's own tools/allowedTools/toolsSettings,
# so read-only and no-commit constraints are enforced by Kiro, not by prose.
# Built against kiro.dev/docs/cli (June 2026). Kiro exposes no token/cost data in
# chat output, so events.jsonl entries carry duration only.
set -euo pipefail
source "$(cd "$(dirname "$0")/.." && pwd)/lib/common.sh"

role="${1:?usage: kiro.sh <planner|implementer|reviewer> <task_dir> <workdir>}"
td="${2:?}"; wd="${3:?}"
name=$(basename "$td")
rel=".tasks/$name"
sys="$HARNESS_HOME/roles/$role.md"
[ -f "$sys" ] || die "unknown role: $role"
KIRO_BIN="${KIRO_BIN:-$(command -v kiro-cli || command -v kiro || true)}"
[ -n "$KIRO_BIN" ] || die "kiro-cli not found on PATH (https://kiro.dev/docs/cli)"
mkdir -p "$td/report"

agent="harness-$role"
agent_dir="${KIRO_AGENT_DIR:-$HOME/.kiro/agents}"   # global: keeps work repos clean for G2
mkdir -p "$agent_dir"
model="${HARNESS_REVIEWER_MODEL:-}"                  # set by bin/harness for cross-model review

# (Re)generate the agent config each run so role-file edits always take effect.
# If your Kiro version rejects the tool names, swap read/write/shell for
# fs_read/fs_write/execute_bash — both appear in Kiro's docs.
python3 - "$agent_dir/$agent.json" "$sys" "$role" "$model" <<'PY'
import json, sys
out, prompt_file, role, model = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
cfg = {
    "name": "harness-%s" % role,   # REQUIRED by kiro-cli despite docs saying optional
    "description": "harness %s — generated by adapters/kiro.sh, do not edit" % role,
    "prompt": "file://" + prompt_file,
    "tools": ["read", "write", "shell"] if role == "implementer" else ["read", "shell"],
}
cfg["allowedTools"] = list(cfg["tools"])  # non-interactive mode fails fast on untrusted tools
if role == "implementer":
    cfg["toolsSettings"] = {"shell": {
        "deniedCommands": ["git commit.*", "git push.*", "git merge.*"],
        "autoAllowReadonly": True,
    }}
else:  # planner and reviewer are read-only: search/inspect commands only
    cfg["toolsSettings"] = {"shell": {
        "allowedCommands": ["rg .*", "ls .*", "find .*", "wc .*",
                            "git diff.*", "git status.*", "git log.*"],
        "autoAllowReadonly": True,
    }}
if role == "reviewer" and model:
    cfg["model"] = model
json.dump(cfg, open(out, "w"), indent=2)
PY

# Runs kiro non-interactively, saves the raw transcript, emits the usage event,
# prints the ANSI-stripped response on stdout. The role file is inlined into the
# prompt (as well as living in the agent config) — Kiro has no equivalent of
# --append-system-prompt, and the config's file:// prompt alone proved too weak
# to hold the output-format contract.
run_kiro() {
  local tsf="$td/report/$role-transcript.kiro.txt" t0 mjson esc full_prompt
  full_prompt="$(printf 'YOUR ROLE AND OUTPUT CONTRACT — follow exactly:\n\n%s\n\n---\n\nTASK:\n%s' "$(cat "$sys")" "$prompt")"
  t0=$(date +%s)
  (cd "$wd" && "$KIRO_BIN" chat --no-interactive --agent "$agent" "$full_prompt") \
    > "$tsf" 2> "$td/report/$role-kiro.err" \
    || die "kiro run failed — see $rel/report/$role-kiro.err"
  # A config kiro can't load means a silent fallback to default permissions —
  # the role's read-only/no-commit guarantees were NOT applied. Refuse the output.
  if grep -qiE 'is invalid|no agent with name|falling back' "$td/report/$role-kiro.err"; then
    die "kiro did not load the $agent config — role permissions were NOT applied. See $rel/report/$role-kiro.err"
  fi
  mjson="null"; [ -n "$model" ] && mjson="\"$model\""
  printf '{"ts":"%s","phase":"%s","adapter":"kiro","model":%s,"cost_usd":null,"duration_ms":%d}\n' \
    "$(date +%Y-%m-%dT%H:%M:%S)" "$role" "$mjson" "$(( ($(date +%s) - t0) * 1000 ))" \
    >> "$td/report/events.jsonl"
  esc=$(printf '\033')
  sed "s/${esc}\[[0-9;]*[a-zA-Z]//g" "$tsf"
}

case "$role" in
  spec-splitter)
    info "spec splitter (kiro, fresh context, read-only) → report/spec-split.md"
    prompt="Partition the spec at $rel/SPEC.md into independently shippable \
specs per your role's rules — reorganize only, never add intent. Print ONLY \
the marker-delimited spec blocks; your response is saved verbatim."
    run_kiro > "$td/report/spec-split.md"
    ;;
  spec-critic)
    info "spec critic (kiro, fresh context, read-only) → report/spec-review.md"
    prompt="Critique the draft specification at $rel/SPEC.md before human \
approval. Survey this repository to check the spec against reality. Print ONLY \
the critique in your agent prompt's format, ending with an ASSESSMENT line — \
your response is saved verbatim as $rel/report/spec-review.md."
    [ -f "$td/report/spec-review.prev.md" ] && prompt="$prompt This is a \
re-critique: your prior critique is at $rel/report/spec-review.prev.md and the \
human has revised the spec since — apply your role's re-critique rule."
    run_kiro > "$td/report/spec-review.md"
    info "wrote $td/report/spec-review.md"
    ;;
  planner)
    info "planner (kiro, fresh context, read-only) → PLAN.md"
    prompt="Read $rel/SPEC.md, survey this repository, and produce the PLAN.md \
content for this task. Print ONLY the plan markdown in the exact format your \
agent prompt defines — your response is saved verbatim as $rel/PLAN.md."
    run_kiro > "$td/PLAN.md"
    info "wrote $td/PLAN.md"
    ;;
  implementer)
    info "implementer (kiro, write access, scoped by G2) → working tree"
    prompt="Implement the task defined in $rel/SPEC.md according to $rel/PLAN.md. \
Touch only files within your task's declared Scope. Run this repo's own \
lint/tests before finishing. Leave all changes uncommitted."
    [ -f "$td/report/g3-feedback.md" ] && prompt="$prompt A previous attempt was \
rejected by the human reviewer; read $rel/report/g3-feedback.md and address it."
    [ -f "$td/report/review.md" ] && prompt="$prompt Prior reviewer findings are \
in $rel/report/review.md."
    run_kiro | tee "$td/report/implement.log"
    ;;
  reviewer)
    info "reviewer (kiro, fresh context, read-only${model:+, model=$model}) → report/review.md"
    prompt="Review the current uncommitted diff ('git diff HEAD' plus untracked \
files) against $rel/SPEC.md and $rel/PLAN.md. You did not write this code. \
Print ONLY the review in your agent prompt's format, ending with a VERDICT \
line — your response is saved verbatim as $rel/report/review.md."
    run_kiro > "$td/report/review.md"
    info "wrote $td/report/review.md"
    ;;
  *)
    die "unknown role: $role"
    ;;
esac
